### ISSUE TITLE
pifs

### ISSUE THREAD

**Issue by JDWoodcock** [meta-analyses/meta-analysis-shiny#2]
we need to calculate population impacts fractions for each of the diseases- see attached
[PIF.xlsx](https://github.com/meta-analyses/meta-analysis-shiny/files/407310/PIF.xlsx)

**Comment by JDWoodcock** [comment]
can we have flexible choice of PI with it showing what % of the population have exposure above that level.

**Comment by usr110** [comment]
This issue has been resolved in https://github.com/meta-analyses/meta-analysis-shiny/commit/80454cccc927ca2d19cfd18c0ec532e0d57759b7.
Please create a separate issue for additional changes (creating a new issue for https://github.com/meta-analyses/meta-analysis-shiny/issues/2#issuecomment-246956244).
